const TWITTER_REQUEST_URL = 'TWITTER_REQUEST_URL'
const TWITTER_AUTHORIZE_URL = 'TWITTER_AUTHORIZE_URL'
const TWITTER_ACCESS_URL = 'TWITTER_ACCESS_URL'
const TWITTER_CONSUMER_KEY = 'TWITTER_CONSUMER_KEY'
const TWITTER_CONSUMER_SECRET = 'TWITTER_CONSUMER_SECRET'
const TWITTER_SCOPE_URL = 'TWITTER_SCOPE_URL'
const TWITTER_APP_NAME = 'TWITTER_APP_NAME'
const TITTER_ACCESS_TOKEN = 'TWITTER_ACCESS_TOKEN'
const TWITTER_ACCESS_TOKEN_SECRET = 'TWITTER_ACCESS_TOKEN_SECRET'

export {
  TWITTER_REQUEST_URL,
  TWITTER_AUTHORIZE_URL,
  TWITTER_ACCESS_URL,
  TWITTER_CONSUMER_KEY,
  TWITTER_CONSUMER_SECRET,
  TWITTER_SCOPE_URL,
  TWITTER_APP_NAME,
  TITTER_ACCESS_TOKEN,
  TWITTER_ACCESS_TOKEN_SECRET
}
